[package]
name = "nitrate-bench"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[dev-dependencies]
criterion = "0.5"
nitrate-utils = { path = "../nitrate-utils" }

[[bench]]
name = "sha2_ref"
harness = false