[package]
name = "nitrate-config"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_with = "3.11"
toml = "0.8"
config = "0.14"
thiserror = "1.0"