name: CI

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    name: Format, Clippy, and Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust toolchain (stable)
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt

      - name: Cache cargo registry, index, and target
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Cargo fmt check
        run: cargo fmt --all -- --check

      - name: Cargo clippy with dummy backend
        run: cargo clippy --workspace --all-targets --features nitrate-core/gpu-dummy -- -D warnings

      - name: Cargo clippy with CUDA backend
        run: cargo clippy --workspace --all-targets --features nitrate-core/gpu-cuda -- -D warnings

      - name: Cargo test (build only)
        run: cargo test --workspace --features nitrate-core/gpu-dummy --no-run

      - name: Cargo test (run)
        run: cargo test --workspace --features nitrate-core/gpu-dummy -- --nocapture

  build_cli:
    name: Build CLI (dummy backend)
    runs-on: ubuntu-latest
    needs: check

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust toolchain (stable)
        uses: dtolnay/rust-toolchain@stable

      - name: Cache cargo registry, index, and target
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Build nitrate-cli with dummy backend
        run: cargo build -p nitrate-cli --release --features nitrate-core/gpu-dummy
